// <auto-generated />
using System;
using Autoware.Recall.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Autoware.Recall.Infrastructure.Migrations
{
    [DbContext(typeof(RecallContext))]
    partial class RecallContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Autoware.Recall.Domain.AggregatesModel.RecallAggregate.Models.Chassi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoChassi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chassi");
                });

            modelBuilder.Entity("Autoware.Recall.Domain.AggregatesModel.RecallAggregate.Models.ChassiRecall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChassiId")
                        .HasColumnType("int");

                    b.Property<string>("Concessionaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecallId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChassiId");

                    b.HasIndex("RecallId");

                    b.ToTable("ChassiRecall");
                });

            modelBuilder.Entity("Autoware.Recall.Domain.AggregatesModel.RecallAggregate.Models.Recall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recall");
                });

            modelBuilder.Entity("Autoware.Recall.Domain.AggregatesModel.RecallAggregate.Models.ChassiRecall", b =>
                {
                    b.HasOne("Autoware.Recall.Domain.AggregatesModel.RecallAggregate.Models.Chassi", "Chassi")
                        .WithMany()
                        .HasForeignKey("ChassiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Autoware.Recall.Domain.AggregatesModel.RecallAggregate.Models.Recall", "Recall")
                        .WithMany()
                        .HasForeignKey("RecallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chassi");

                    b.Navigation("Recall");
                });
#pragma warning restore 612, 618
        }
    }
}
